### ISSUE TITLE
Where is RITEyes_helper?

### ISSUE THREAD

**Issue by huaji98** [RSKothari/EllSeg#1]
Hi, I found no RITEyes_helper file.

**Comment by RSKothari** [comment]
Hi @huaji98 the `RITEyes_helper` file is part of old code which is not used anymore. Please ignore files which called `RITEyes_helper`. I also suggest using the [bitbucket repo](https://bitbucket.org/RSKothari/ellseg/src/master/) because a bug was identified and I had fixed it in the other repo.

**Comment by Heena-S-Patel** [comment]
from RITEyes_helper.subpixel_python.finalDetector_0 import finalDetector
ModuleNotFoundError: No module named 'RITEyes_helper'

Could You please assist to get finalDetector module?

**Comment by RSKothari** [comment]
@Heena-S-Patel Please use this repo and file: https://bitbucket.org/RSKothari/ellseg/src/master/test.py

**Comment by Heena-S-Patel** [comment]
Thank you so much for your response...

I want to pre-process the dataset. Hence want to run files from dataset
generation.

**Comment by partialQ** [comment]
I also can't use the function-'getfinalDetector', could you give us the file RITEyes_helper or another preprocess file that can extract the dataset RITEyes?

**Comment by milleniums** [comment]
I also need this file to preprocess data.
